package com.huochangfeng.myexperiment.epub.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.huochangfeng.myexperiment.epub.db.BookInfo;
import com.huochangfeng.myexperiment.epub.db.Chapter;

import com.huochangfeng.myexperiment.epub.db.BookInfoDao;
import com.huochangfeng.myexperiment.epub.db.ChapterDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookInfoDaoConfig;
    private final DaoConfig chapterDaoConfig;

    private final BookInfoDao bookInfoDao;
    private final ChapterDao chapterDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookInfoDaoConfig = daoConfigMap.get(BookInfoDao.class).clone();
        bookInfoDaoConfig.initIdentityScope(type);

        chapterDaoConfig = daoConfigMap.get(ChapterDao.class).clone();
        chapterDaoConfig.initIdentityScope(type);

        bookInfoDao = new BookInfoDao(bookInfoDaoConfig, this);
        chapterDao = new ChapterDao(chapterDaoConfig, this);

        registerDao(BookInfo.class, bookInfoDao);
        registerDao(Chapter.class, chapterDao);
    }
    
    public void clear() {
        bookInfoDaoConfig.getIdentityScope().clear();
        chapterDaoConfig.getIdentityScope().clear();
    }

    public BookInfoDao getBookInfoDao() {
        return bookInfoDao;
    }

    public ChapterDao getChapterDao() {
        return chapterDao;
    }

}
